### PR TITLE
Support official blueprints automatic update

### PR DESCRIPTION
**Pull request by sahbi-ktifa**
Add automatic update support for Kotlin and Vue.js blueprint.

WARNING: Sample app repositories must be created before this to be merged.

### CODE REVIEW

**Comment by jdubois** [comment]
@sahbi-ktifa the repositories are created:

https://github.com/jhipster/jhipster-sample-app-vuejs
https://github.com/jhipster/jhipster-sample-app-kotlin

Could you do PRs on both to add the `.yo-rc.json`, and maybe some JDL?

**Comment by sahbi-ktifa** [comment]
Sure, I'll do that!
Thanks!

**Comment by sahbi-ktifa** [comment]
@jdubois Repositories are both empty, I can't PR anything to it. Could you either give me the right to do it or add a dummy readme please?

**Comment by jdubois** [comment]
@sahbi-ktifa done, I added a sample `.yo-rc.json` in each

**Comment by sahbi-ktifa** [comment]
Repositories updated :)

**Comment by jdubois** [comment]
Thanks, we'll see how it works with the next release :-D

**Pull request merged**
