### PR TITLE
Add Couchbase sample app

### PR DESCRIPTION
**Pull request by hdurix**
Before accepting this Pull Request, just be sure the new repository has been created: https://github.com/jhipster/jhipster-sample-app-couchbase.
And add the `.yo-rc.json` with Couchbase I think (I can do it if you create the repo).

Thanks!

### CODE REVIEW

**Comment by jdubois** [comment]
@hdurix it's merged and the project is created, but there is a big issue: it looks like `./mvnw test` do not work on the sample project!!
Could you check?

**Comment by hdurix** [comment]
Yes let me check

**Comment by hdurix** [comment]
I don't understand, I have the same error in a newly generated app.

Integration tests with Couchbase can not be launched (`Connection refused: localhost/127.0.0.1:11210`).

It seems to be linked to the new jhipster-dependencies release: as soon as I change it in `pom.xml`:
- the tests are running with version `2.0.2`
- the tests are not running with version `2.0.3`

But I can't understand, if the error is really that, why the Travis build is not failing... (for instance https://travis-ci.org/jhipster/generator-jhipster/jobs/380706690 is ok).

I will create an issue on the generator.

**Comment by hdurix** [comment]
Maybe because of this?

https://github.com/jhipster/generator-jhipster/blob/master/travis/scripts/03-replace-version-generated-project.sh#L15

**Pull request merged**
